### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ScamShop** [ScamShop/Telegram-Nuker#5]
How can fix that (“/usr/bin/python3 -u -c “import figlet, tokenize;file=’/tmp/pip-build-3b0_1gh5/psutil/Ban_all.py’;f=getattr(tokenize, ‘open’, open)(file);code=f.read().replace(’\r\n’, ‘\n’);f.close();exec(compile(code, file, ‘exec’))” install --record /tmp/pip-5ytpn09j-record/install-record.txt --single-version-externally-managed --compile” failed with error code 1 in /tmp/pip-build-3b0_1gh5/psutil/")

**Comment by OnlyTrueStar** [comment]
install the requirments
